[item]
guid = -ytJ0No9ZsM
title = "How to Fix BAD POSTURE (FOREVER!)"
description = "My Calisthenics Programs: \n👉 https://fitnessfaqs.com \n\nFollow Me: \nhttps://www.instagram.com/FitnessFAQs\nhttps://www.facebook.com/FitnessFAQs\n\nMost of us spend the majority of our day sitting behind a computer or using a mobile phones. We tend to sit in a hunched posture which causes havoc to our neck, shoulders and back.\n\nPain, weakness and tightness is all very common when sitting all day.\n\nThere is no perfect posture, there is no poor posture, there is no bad posture, the problem is we don't move enough. A lack of movement causes our joints to become stiff and muscles to lose strength. \n\nI'm going to show you the best exercises and stretches to improve mobility and flexibility. You'll learn how to fix your posture, find relief from pain and correct movement dysfunction. \n\nIf you found this video helpful share it with a friend."
author = FitnessFAQs
source = https://www.youtube.com/channel/UC1CVzH-XVr3E-kTT6D8hhfg
link = https://www.youtube.com/watch?v=-ytJ0No9ZsM
category = "Sports"
pubdate = Thu, 31 Oct 2019 00:00:00 -0000
enclosure = -ytJ0No9ZsM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/-ytJ0No9ZsM/maxresdefault.webp

