[item]
guid = 1eqKau93EPw
title = "Big Chest By Bodyweight Only"
description = "My Calisthenics Programs:\n👉 https://fitnessfaqs.com\n\nFollow Me:\nhttps://www.instagram.com/FitnessFAQs\nhttps://www.facebook.com/FitnessFAQs"
author = FitnessFAQs
source = https://www.youtube.com/channel/UC1CVzH-XVr3E-kTT6D8hhfg
link = https://www.youtube.com/watch?v=1eqKau93EPw
category = "Sports"
pubdate = Thu, 03 Dec 2015 00:00:00 -0000
enclosure = 1eqKau93EPw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/1eqKau93EPw/maxresdefault.webp

