[item]
guid = At0mMAHqWrQ
title = "How To DRAGON FLAG Tutorial (Beginner & Advanced Progressions)"
description = "🔥 Become a Calisthenics Pro\n👉 https://fitnessfaqs.com\n\nFollow Me: \nhttps://www.instagram.com/FitnessFAQs\nhttps://www.facebook.com/FitnessFAQs\n\nThis FitnessFAQs workout tutorial is going to cover how to dragon flag. We will be discussing the best ab and core progression from beginner to advanced.\n\nThe dragon flag exercise was made popular by both bruce lee and rocky. It's an excellent exercise because it involves a hollow body, anti-extension based posture and technique.\n\nThere are several variations from easy to hard including eccentrics or negatives, full range of motion, extensions and also isometric holds. Anyone involved in calisthenics or bodyweight training will benefit from mastering this exercise.\n\nA guideline for how to use dragon flags in your calisthenics core and ab workout is provided at the end. For those of you reading this, show some love by liking the video and dropping a comment. Don't forget to subscribe and turn on the bell notifications to never miss a new video."
author = FitnessFAQs
source = https://www.youtube.com/channel/UC1CVzH-XVr3E-kTT6D8hhfg
link = https://www.youtube.com/watch?v=At0mMAHqWrQ
category = "Sports"
pubdate = Thu, 22 Apr 2021 00:00:00 -0000
enclosure = At0mMAHqWrQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/At0mMAHqWrQ/maxresdefault.jpg

