[item]
guid = oj6MNlqkRfA
title = "How to Fix Chest Pain From Dips"
description = "My Calisthenics Programs: \n👉 https://fitnessfaqs.com \n\nFollow Me: \nhttps://www.instagram.com/FitnessFAQs\nhttps://www.facebook.com/FitnessFAQs\n\nIn this video we'll be covering how to fix chest pain from dips. Costochondritis is painful when breathing, located in the middle of the chest or sternum and can be uncomfortable. This condition is generally brought on with weighted dips or doing too many dips too soon. The symptoms can be felt during or after doing dips. \n\nFitnessFAQs will be covering chest pain relief exercises you can do including stretches, mobility and strength. Costochondritis is a self limiting condition which will get better over time. Abstain from painful exercises to allow inflammation to settle."
author = FitnessFAQs
source = https://www.youtube.com/channel/UC1CVzH-XVr3E-kTT6D8hhfg
link = https://www.youtube.com/watch?v=oj6MNlqkRfA
category = "Sports"
pubdate = Thu, 16 Aug 2018 00:00:00 -0000
enclosure = oj6MNlqkRfA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/oj6MNlqkRfA/maxresdefault.webp

