[item]
guid = P99HPnWIrxQ
title = "The 6 Best Bodyweight Ab Exercises"
description = "My Calisthenics Programs:\n👉 https://fitnessfaqs.com\n\nFollow Me:\nhttps://www.instagram.com/FitnessFAQs\nhttps://www.facebook.com/FitnessFAQs\n\nMUSIC: Title: Bustre - Combine\nVideo Link: https://www.youtube.com/watch?v=ig44rDYo8IM\nBeatport Download Link: https://pro.beatport.com/release/combine/1521822\nLabel Channel: http://www.youtube.com/monstercat"
author = FitnessFAQs
source = https://www.youtube.com/channel/UC1CVzH-XVr3E-kTT6D8hhfg
link = https://www.youtube.com/watch?v=P99HPnWIrxQ
category = "Sports"
pubdate = Thu, 28 May 2015 00:00:00 -0000
enclosure = P99HPnWIrxQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/P99HPnWIrxQ/maxresdefault.webp

