[item]
guid = Qlfd9kbLuxw
title = "5 Ways to Master the Hollow Body Exercise"
description = "Master Your Body ➤ http://www.fitnessfaqs.tv \n\nFOLLOW FITNESSFAQS:\nhttp://www.instagram.com/FitnessFAQs\nhttp://facebook.com/FitnessFAQs\n\nTRAINING PROGRAMS:\nhttp://bodybyrings.com\nhttp://planche.pro\nhttp://limitlesslegs.com\n\nMUSIC:\nhttps://soundcloud.com/sappheirosmusic/celestial\n\nIn this video Daniel Vadnal of FitnessFAQs will teach you how to make progress beyond the regular hollow body hold exercise. Being able to sustain a hollow body is essential for advanced gymnastic exercises. If the anterior core is weak, the lower back will arch and creating a disconnect between the arms and legs during a skill or exercise. Using a rocking motion, bands and or weight will create a de-stabilising effect forcing the core to work harder. It is a must to continue to challenge yourself when an exercise gets too easy. This video shows 5 different ways to challenge the core and will allow you to construct workouts of an appropriate intensity."
author = FitnessFAQs
source = https://www.youtube.com/channel/UC1CVzH-XVr3E-kTT6D8hhfg
link = https://www.youtube.com/watch?v=Qlfd9kbLuxw
category = "Sports"
pubdate = Thu, 23 Mar 2017 00:00:00 -0000
enclosure = Qlfd9kbLuxw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/Qlfd9kbLuxw/maxresdefault.webp

