[item]
guid = uZqTUwq96iU
title = "The BEST HOLLOW BODY Progressions - Beginner to Advanced"
description = "🔥 The #1 Calisthenics Programs\n➡️ http://fitnessfaqs.com/\n\nFollow Me: \nhttps://www.instagram.com/FitnessFAQs\nhttps://www.tiktok.com/@fitnessfaqs.com\nhttps://www.facebook.com/FitnessFAQs\n\nGet ready for the best hollow body hold tutorial, beginner to advanced progressions.\n\nThe hollow body exercise is an important abs workout for calisthenics, crossfit and gymnastics.\n\nFitnessFAQs will show how to use this exercise with no equipment for at home workouts. We don't need a gym or weights to get effective results.\n\nBuilding a strong core and six pack abs requires intelligent nutrition first and foremost. Next you need to be consistent with calisthenics. You will learn how to use the hollow body hold working from easy to hard, beginner to advanced."
author = FitnessFAQs
source = https://www.youtube.com/channel/UC1CVzH-XVr3E-kTT6D8hhfg
link = https://www.youtube.com/watch?v=uZqTUwq96iU
category = "Sports"
pubdate = Fri, 02 Apr 2021 00:00:00 -0000
enclosure = uZqTUwq96iU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/uZqTUwq96iU/maxresdefault.jpg

