[item]
guid = WgbTXHi3aNo
title = "The BEST Six Pack Abs Exercise (STRENGTH & SIZE)"
description = "🔥 My Calisthenics Workout\n✅ https://fitnessfaqs.com/programs\n\nFollow Me: \nhttps://www.instagram.com/FitnessFAQs\nhttps://www.facebook.com/FitnessFAQs\n\n#abs #fitness"
author = FitnessFAQs
source = https://www.youtube.com/channel/UC1CVzH-XVr3E-kTT6D8hhfg
link = https://www.youtube.com/watch?v=WgbTXHi3aNo
category = "Sports"
pubdate = Thu, 15 Jul 2021 00:00:00 -0000
enclosure = WgbTXHi3aNo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/WgbTXHi3aNo/hqdefault.jpg

